export const GITHUB_LOGIN_SUCCESS = 'github_login_success'
export const GITHUB_LOGIN_FAILED = 'github_login_failed'
export const GITHUB_GETREPO_SUCCESS = 'github_getrepo_success'
export const GITHUB_GETREPO_FAILED = 'github_getrepo_failed'
export const CURRENT_ORG = 'current_org'
export const GITHUB_GETORG_SUCCESS = 'github_getorg_success'
export const GITHUB_GETORG_FAILED = 'github_getorg_failed'
